### ISSUE TITLE
Fix user dropdown

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#10]
- [ ] Better implementation of the li, also in responsive.

**Comment by RobZoneNet** [comment]
I believe I fixed it.  
![screen shot 2015-05-12 at 6 04 31 pm](https://cloud.githubusercontent.com/assets/103745/7599590/64b8e5ce-f8d1-11e4-8fbc-cd10ec6fee7a.png) I hope this is what you had in mind @sneridagh  It is currently mobile since it is thrown into the hamburger menu navigation.  I am going to close this. You can open it if it isn't what you were thinking.
