### ISSUE TITLE
Add plone.app.vulnerabilities

### ISSUE THREAD

**Issue by sneridagh** [plone/ploneorg.core#14]

**Comment by gforcada** [comment]
Current setup.py already depends on it, is there anything else that needs to be done?

**Comment by fulv** [comment]
I activated it from http://new.plone.org/prefs_install_products_form.
If my PR https://github.com/plone/plone.app.vulnerabilities/pull/5 gets merged, then we'd have all the latest Plone versions available.

If we decide to use this, someone would have to manually create the "Hotfix" content items for all hotfixes listed here: https://plone.org/security/hotfixes/.  Unless it's the same content type on the old site, in which case they could be migrated.  But it doesn't look like it's the same.

I could do the manual (copy & paste) migration.  There are a couple of issues, though, for example, right now it seems like you can only upload one file, while some hotfixes have multiple versions:  https://plone.org/products/plone-hotfix/releases/20130618

**Comment by fulv** [comment]
I'll formulate a direct question:  Does the old plone.org site use plone.app.vulnerabilities, or another custom content type from which plone.app.vulnerabilities is derived, for hotfixes, like https://plone.org/security/20131210?

Can one of you who has access to plone.org verify this?

Based on the answer, we can decide what to do with the existing hotfixes.

**Comment by aclark4life** [comment]
Yup: https://github.com/plone/Products.PloneOrg/blob/master/setup.py#L53

**Comment by fulv** [comment]
Awesome!  Then the existing hotfixes can should be easily migratable.

**Comment by fulv** [comment]
I will post a comment here for exact export path.

**Comment by fulv** [comment]
@polyester: the hotfix content items seem to live here:
https://plone.org/security

If you do a zexp export from that folder, it'll include a bunch of other stuff, but I think it's probably our best bet to get started.  If that does not import cleanly due to the presence of other types we don't have installed, we'll deal with those cases as they arise.

Also, for good measure, you might want to export this folder:  https://plone.org/products/plone/security

Thanks!

**Comment by gforcada** [comment]
@fulv should we just export them with everything else? @sneridagh worked quite a lot on the export, so exporting some more content should be that much work and it will give us a clean migration, I'm no fan of zexp... :)

**Comment by gforcada** [comment]
sorry accidental closing...

**Comment by fulv** [comment]
@gforcada I proposed zexp, because in theory the hotfix content items should be backed by exactly the same product in both sites, so my reasoning was that if it the exp/imp works for free, why pay for it?  I'd like to give it a try, and if (as so often) zexp lets us down, then we'll move on to plan b.

**Comment by gforcada** [comment]
@fulv I was suggesting that based on your *" it'll include a bunch of other stuff, but I think it's probably our best bet"*, but if it's a 1:1 thing then sure, give it a try at new.plone.org
