### ISSUE TITLE
planet.plone.org without CSS

### ISSUE THREAD

**Issue by keul** [plone/ploneorg.core#149]
Not sure where planet.plone.org issues must be reported, but I fear that recent plone.org migration has broken the blog site.

http://planet.plone.org/

It seems that it's requesting for plone.org/plone.css that is now an empty resource

**Comment by macagua** [comment]
@keul 

If change the URL CSS link from:
```css
<link rel="stylesheet" href="http://plone.org/plone.css" type="text/css" media="screen" charset="utf-8">
```
To this new URL: 
```css
<link rel="stylesheet" href="http://old.plone.org/plone.css" type="text/css" media="screen" charset="utf-8">
```

This screenshot was made with my Weddev Inspect Tool:

![screenshot from 2016-05-15 20 08 33](https://cloud.githubusercontent.com/assets/185395/15277673/04edf5a4-1ad5-11e6-90d8-6d783fb4c0e8.png)

@tkimnguyen I can help with this minimal change, if assign to me this issue, but I can access to deploy this improvement.

**Comment by svx** [comment]
@macagua you do not need to access anything, it is enough to fix that in https://github.com/plone/planet.plone.org, which I just did with https://github.com/plone/planet.plone.org/commit/f611f98c2b6496e9629f36f2f0caff3e435ccf03 .

Anyway since plone.org is depolyed we should fix the [2.0 branch](https://github.com/plone/planet.plone.org/tree/version_2.0) and deploy the new setup asap :)

**Comment by tkimnguyen** [comment]
@svx ok to close this issue?

**Comment by macagua** [comment]
@svx Ok I understand, thanks :-)

**Comment by macagua** [comment]
@tkimnguyen I believe that this issue is done, please check out http://planet.plone.org/

**Comment by svx** [comment]
@tkimnguyen yeah it is fixed, closing this now :)
