### ISSUE TITLE
migrate country info?

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#154]
@macagua asks if we will be migrating https://old.plone.org/countries/

**Comment by macagua** [comment]
@tkimnguyen Yes please :-) 

For example, I manage the following sections:
- https://old.plone.org/countries/ve
- https://old.plone.org/countries/conosur

And they are very useful because when our own local servers are dropped or maintenance, we always have information online about our Spanish local communities in the Main Community website Plone.org

Other Spanish local community section is https://old.plone.org/countries/mx

**Comment by polyester** [comment]
hmm, it's a bit tricky. Some of the country pages are well maintained, but most of them are extremely outdated, and incorrect. That's why it was all consolidated into one page at
https://plone.org/support/local-user-groups

But I can see the usecase. Let's think about it for a bit, and come up with a solution that allows for countrypages but only if there is a clear maintainer, so that the pages get maintained. Logically they should go under /support, imo.

**Comment by tkimnguyen** [comment]
/me cringes looking at the Oshkosh user group entry... [goes to /edit]

**Comment by tkimnguyen** [comment]
@polyester maybe we could have a workflow that expires content each year, along with an alert email to the maintainer and perhaps to an alternate maintainer (so there is continuity).

**Comment by tkimnguyen** [comment]
https://old.plone.org/countries/be is another one, linked to from http://plone.com/providers/sponsors/affinitic

**Comment by markahuston** [comment]
Kimberly.   PleaSe stop
Your emails to me 🎱

**Comment by rioksane** [comment]
This is so outdated and obsolete, that I think its not worth fixing/migrating anymore. Sorry.
