### ISSUE TITLE
196 add-ons on front page

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#165]
Get a better, defensible number up there :)

**Comment by gforcada** [comment]
Someone added that number already

**Comment by tkimnguyen** [comment]
@gforcada where did the 196 come from? That was my point.

**Comment by gforcada** [comment]
@tkimnguyen oh, sorry I got you totally wrong then, reopening.

**Comment by MrTango** [comment]
It seems static, even for Plone 5.1 there are over 300 add-on's.
We should fix that.

**Comment by tkimnguyen** [comment]
It is static. What's the number you think it should be changed to?

**Comment by MrTango** [comment]
the best would be to get the number for 5.0 from pypi, thats the closest to reality.
Of course there are core packages included which we should count, but there are also packages missing for sure, so something above 300 makes sense. But I still think, we really need a list, like we had on plone.org. The best would be a combination of pypi infos and additional data like a rating, which we don't have on pypi.

We could read all Plone packages from PyPi, show them and allow users to complete the data in wiki style.
We have already a github login, so it's not to hard to contribute then.

**Comment by djay** [comment]
There a lot of possibilities that could be done and there are also things that then rot due to increased moderation and maintenance burden.

Something like some JS on the front page that queries pypi by classifier and gets a number should be low maintenance. If you could exclude the core packages. I don’t think pypi supports excluding certain trove classifiers so I don’t think there is a practical way to exclude listing core packages other than just counting them manually.

Measuring popularity by voting hasn’t resulted in great results in the past particularly as it gets out of date.

**Comment by tkimnguyen** [comment]
@MrTango (hehe, "Mr. T.") I would prefer a simple answer, because then it'll get done. Updating it occasionally by hand is ok. Unless we can find someone who wants to craft a robust solution that works automatically...

**Comment by rioksane** [comment]
I update the number to 319, as the number of Plone 5.2 packages is pypi. Its probably better that the old number 196 that has been there for four years. 

Plone.org will be renewed this year. In the new version, the data needs to update automatically or be not visible at all.

**Comment by MrTango** [comment]
You can now use a flag "addon" to filter for only addon, not core packages.
This might be not the real number, because people need to update there classifiers, but it's getting there.
