### ISSUE TITLE
rename community.plone.org to forum.plone.org

### ISSUE THREAD

**Issue by tkimnguyen** [plone/ploneorg.core#177]
as discussed in #169

**Comment by gforcada** [comment]
Any reason not to just name it FORUM? I see the point for plone.com but all the others look superfluous the ``.plone.org`` suffix

**Comment by tkimnguyen** [comment]
@gforcada sounds reasonable to me. Anyone else want to weigh in? @3dogMcNeill @sneridagh @polyester

**Comment by polyester** [comment]
+1 for making it "plone.com", "documentation", "training" and "forum"

**Comment by macagua** [comment]
+1 "plone.org" like community, "plone.com" for making, "docs.plone.org" for documentation, "training.plone.org" for Plone training and "forum.plone.org" or "plone.org/forum" for community forum.

**Comment by tkimnguyen** [comment]
...and deployed

**Comment by hvelarde** [comment]
I though the idea was to change the subdomain from "community" to "forum".

**Comment by gforcada** [comment]
@hvelarde that's more or less tangential to what is advertised on the black top bar, so a new ticket should be created, no idea where though :-)

**Comment by polyester** [comment]
well, renaming an actual URL has more serious consequences (google, links breaking), not to mention people's muscle memory, so that should not be done without sufficient thinking & discussing. 
And a sufficient volunteer force to watch analytics and the like. Filing a ticket does not automatically increase the volunteer time ;-)

But this change is cosmetic and easily done.

**Comment by davilima6** [comment]
Isn't it a bit misleading to have a well-known subsite called Community to which we don't get to if we click in main website's "Community" link? As @hvelarde, I was +1 in #169 because I thought that was the idea. I agree muscle memory is a downside but we do have a naming conflict and direct 301s for the entire subdomain should be enough, shouldn't it? I mean, what else would we do with Analytics insights?

**Comment by polyester** [comment]
I'm not saying it *shouldn't* be done, just that

- it should probably first be discussed (on community.plone.org, oh irony) and not just on an issuetracker not many people read.
- it can only be done with a time-plan, for which somebody has to take the lead
- as there are probably quite a few internal settings (or possibly even a re-install or so, I have no idea how these Discourse docker thingies work...) this needs time, and willingness, from the AI team. From https://meta.discourse.org/t/change-the-domain-name-or-rename-my-discourse/16098 it looks like it needs at least people with access to a few keys...
- and from other people to make it consistent over plone.com, training.plone.org, docs.plone.org, and other sites.
- and the 301 obviously, but that's the quickest of them all

so it's slightly bigger than just a DNS change you do on a friday at 17:59 (haven't we all done that ;-)
