### ISSUE TITLE
site about add-ons it really confusing

### ISSUE THREAD

**Issue by svx** [plone/ploneorg.core#178]
Hi,

the whole situation about add-ons is really confusing we have:

https://plone.org/download/add-ons/popular-add-ons

and 

https://plone.org/download/add-ons/all-plone-add-ons
## Why is this confusing:

The first link is giving you some information, that is great, but it also misses some really important info, with the current setup, Me as as user thinks, uhh nice all this awesome add-ons, but now I click on one of these links, and hopefully if I do not get a 

> Something went wrong page

 from pypi 

I am getting a site on pypi, well great ! :)

Well, no it is not :), all the pypi add-on sites are looking different, on some it is really hard to find out with which version of Plone they are working, this may enough for devs, bit this is bad for integrators.

So in order to fix that a bit and make it a bit more user friendly it would be IMHO a great improvement to add on https://plone.org/download/add-ons/popular-add-ons, the version of Plone they are working with.

:)

As far as for the second link:

https://plone.org/download/add-ons/all-plone-add-ons, I am wondering if it would be better to:
- remove it completely, for people with less experience, this is horrible confusing, yes both of the two links mentioned on this site.
- to think about a better way to filter and make it look less bad and easier to understand

**Comment by polyester** [comment]
to keep track of discussions: there was already discussion at https://community.plone.org/t/plone-org-add-on-listing/2171/4 and https://community.plone.org/t/paragon-vs-ploneawesome/680/22

**Comment by svx** [comment]
Yes but they are different, at least kind og,  I do not talk about a technical solution I talk about how the wording/info on plone.org is, they are connected true ! But also different one is technical, one is how you write and publish content

**Comment by tkimnguyen** [comment]
@svx the page https://plone.org/download/add-ons/all-plone-add-ons is something I created so that it all looks good when you are viewing https://plone.org/download/add-ons (which has "all content" display view)

If your objection is that https://plone.org/download/add-ons/all-plone-add-ons is its own page, we could just add those two links to the bottom of the page https://plone.org/download/add-ons/popular-add-ons but I figured they might get lost as people edit https://plone.org/download/add-ons/popular-add-ons.

The whole add-on page thing is a pita and it would be nice if people were willing to help contribute to it. At the moment that's as simple as making a PR for https://github.com/plone/paragon.addons/blob/master/add-ons.html but I notice no PRs since May 10 :)

**Comment by svx** [comment]
@tkimnguyen the fact that we have both oft hem online, 'just' confuses visitors, they do not care about 'different views' and the should not.
So yeah this should be solved in a different way. 

And I am sorry, I am really thankfully about all the stuff you are doing here, but I just disagree with https://github.com/plone/paragon.addons completely IMHO I can see what you are trying to solve. but I think that is the wrong way for so many reasons :)

- we have a cms, use it
- way to complex, no docs, no good explanation
- not flexible
- too much focus on devs  
- ...

Maybe I am wrong, but I do not see the need of doing it in that way at all :)

Which brings me to the simple base question:

Who is the audience of the add-ons page ? For the moment at least this is certainly not for 'a integrator ' right ?

:)

**Comment by djay** [comment]
I have an idea I'm working on to do this differently. Not sure if it will work but the idea is based on doing a census of sites by making it easy to upload what plugins and versions are installed on a given site. Then aggregate information is browsable to see which plugins and versions are most used and which are used together.

**Comment by svx** [comment]
I am just back from some testing, meaning I took some user which I consider audience of the add-on site and let them test the site and wrote down their opinion, I guess no one did that yet ? I will write that down on community in a moment

**Comment by svx** [comment]
Here my findings after i did some testing with user:
https://community.plone.org/t/plone-org-add-on-listing/2171/18

**Comment by rioksane** [comment]
I think this issue could be closed. Look at https://plone.org/download/add-ons, it's now up to date and points to PyPi with working links. Also, the lists of most popular add ons are curated since 2016

Both 

https://plone.org/download/add-ons/popular-add-ons

and

https://plone.org/download/add-ons/all-plone-add-ons

have been hidden from public.
