### ISSUE TITLE
Plone 4.3 LTS

### ISSUE THREAD

**Issue by svx** [plone/ploneorg.core#182]
Hi,

seeing this:

![plone-lts](https://cloud.githubusercontent.com/assets/358860/15963573/677a5576-2f13-11e6-9ecf-975780667df7.png)

make me think that is not ideal in terms of communication, if I use a "LTS" I would like to know *exactly* how long a version is supported, that is one of the reasons I go for LTS, telling user "until Plone 6" is released is not helpful.

When exactly will that be ? How I am supposed to plan? Where is the "official roadmap" and long term overview about future planned releases and versions ?

I am sorry but IMHO in terms of communication this is more harming than doing good.

IMHO we should rewrite or skip that at all, I am not sure if you even want to call 4.3 a LTS ? Personally I would not do that at all.

**Comment by hvelarde** [comment]
please don't start putting unnecessary pressure to the @plone/framework-team: **Plone 6 must be release when is ready** and not on an arbitrary date selected to solve a communication problem.

Plone is OSS; and that's the way it should work; I want new mistakes not to repeat Plone 5 ones.

**Comment by svx** [comment]
@hvelarde You do not get my point, maybe I was not explaining it good enough.

My point is **not** that I want to pressure the @plone/framework-team with anything. I am trying to say that we should be careful with how and what we communicate on plone.org.

If we saying something like "this is lts and will be supported till versions 6 is ready" is that no handy in terms of communication, the point with lts releases is that people can plan and know dates or release that is one of the whole points to have lts versions.

So that is why I am saying **do not use** the term lts, this is all.

I thought that was clear in my first post.

**Comment by gforcada** [comment]
@svx the point is clear and valid and given that the policy for new releases has somewhat changed, it would be good to get that information on that page, so at least the @plone/framework-team and @plone/release-team (I guess is more of the duty of the second one) to decide on official release maintenance.

Do we want to support 4.3.x until Plone 6.0 is out? Or maybe, to be nicer until 6.1?
What about 5.0? Until 5.2 is released (i.e. when there's at least another release in between) or on 5.3/4/5? And what happens when 6 is released? Do we drop support for **all** 5.x versions but the last right away or gradually?

IMHO that should be cleared, which of course can be changed at any time, but at least needs to be clearly documented somewhere and linked to it from relevant places, and the download page is of course such one.

**Comment by jensens** [comment]
Also at the page it looks like Plone 5 has not LTS.

**Comment by esteele** [comment]
I added that, with the intent that we'd continue creating 4.3.x releases until Plone 6 came out. @polyester made some pretty convincing arguments against using the "LTS" term, so I'm fine with removing it.

**Comment by loechel** [comment]
I would go for a communication analog to the debian project, use stable and old stable, both will become support but till next major release is released. 
So it is not about presure on the frameworkteam or release team, it is about clear communications.

**Comment by loechel** [comment]
After communictaion with @svx, @polyester changed to stable / old-stable
