### ISSUE TITLE
Dead link to trademark info in footer of Plone.org

### ISSUE THREAD

**Issue by sgrepos** [plone/ploneorg.core#218]
In the footer of Plone.org, where it says:

"For guidelines on the permitted uses of the Plone trademarks, see [https://plone.org/foundation/logo1](https://plone.org/foundation/logo1)"

The [https://plone.org/foundation/logo1](https://plone.org/foundation/logo1) link is dead. The correct link is at [https://plone.org/foundation/copyright-licensing-logo/](https://plone.org/foundation/copyright-licensing-logo/).

**Comment by tkimnguyen** [comment]
https://old.plone.org/foundation/logo matches identically https://plone.org/foundation/copyright-licensing-logo/archives/the-plone-logo but since the latter is now part of an archives folder I created a redirect from https://plone.org/foundation/logo to https://plone.org/foundation/copyright-licensing-logo/
