### ISSUE TITLE
general overview of the website structure

### ISSUE THREAD

**Issue by gforcada** [plone/ploneorg.core#25]
To make things easier for everyone willing to contribute, it would be great if we have some words about the information architecture of the website.

Something like:
- front page for... (?)
- news items for, er.. news
- event items for, er.. events
- sprints, for everything related to sprints (an event should be created for each of them automatically)
- teams descriptions
- plone contributors
- foundation thingies
- plone releases (or should that be a regular news items?)
- the mozilla like landing page for new contributors
- ... ?

An .rst on the repo maybe is enough

**Comment by djay** [comment]
Given that plone.org will always rank higher and all existing links point
there, the first issue to overcome is how to get visitors who we don't want
to frightened by the community aspect to go to plone.com?

Believe me this is a big issue. If I tell my customers I'm selling plone
and they Google it they will read plone.org first guaranteed. Pretty much
nullifies the going work gone into plone.com.

IMO The best answer would be to have a single site, redirect plone.com to
plone.org and use plone.org/community since those seeking community are not
so easily freighted by a slicker marketing message on the home page. They
will just be presently surprised to find Plone is actually foundation
supported once they click through.
Bonus is we don't need a new theme.

**Comment by tkimnguyen** [comment]
I have started pointing people directly to Plone.com when they need an overview of Plone and why use Plone.

**Comment by gforcada** [comment]
@djay thanks for your input, we will take that into consideration, but that's completely tangential to what I was asking on this ticket.

During Sorrento a team was created to work on the new plone website, yesterday we did a hangout to sync all of us and set some goals and this ticket is just about to get a better overview of the information architecture that this new plone.org will have.

Big buttons or fancy *"first time here? maybe you want to see showcases/business-like explanation of plone, please go to plone.com"* can be done afterwards.

The ideas of the new plone.org are quite stable and we are working on them, you are always welcome to grab a ticket from this repository and work on it.

**Comment by jensens** [comment]
what the state of taking the plip-process away from dev.plone.org to new plone.org?

**Comment by gforcada** [comment]
@jensens create an issue for that, but if I got it right I think the idea is to use github and not plone.org, not 100% sure of it though...

**Comment by jensens** [comment]
ok, i'd prefer github too. i just know there we're plans to use plone.org.

**Comment by tkimnguyen** [comment]
@jensens @gforcada yesterday I changed the front page of dev.plone.org to say that new issues should be created on github. Hope that's ok.

**Comment by tkimnguyen** [comment]
@gforcada in your original post above the list you have looks good. An immediate question: do we want to retain mostly the same content structure to keep old links/URLs mostly working?

- the front page should be an introduction to the .org site vs. the .com site, and describe briefly what's on the site.
- news and events are of course good to have 
- teams, sprints and contributors maybe should be under one "Contributing" folder/tab with that nice welcome page you suggest modelled on Mozilla's
- Foundation should have a separate top level folder/tab :) though one could argue that instead of Foundation having its own tab there should be one top level "Organization" folder/tab with Foundation being under that if it's ok to throw off longstanding URLs...
- a top level "Software" folder/tab, under which two items: Plone and add-ons, the add-ons item showing mostly the feed from paragon.plone.org

I hope that's the feedback you were looking for. :)

**Comment by djay** [comment]
I think the how to contribute content and how to raise bugs needs to be moved somewhere.

I was thinking this section should be expanded in the documentation?
http://docs.plone.org/askforhelp.html

or will dev.plone.org always remain?

I think it would also be helpful to provide documentation on how to make a good feature request or bug report. Possibly some templates you can copy and paste. Is docs the best place for that?

**Comment by tkimnguyen** [comment]
I believe dev.plone.org is meant to go away

**Comment by polyester** [comment]
dev.plone.org is on the way out. It'll be some time, we still need to get the useful content out, but it's going the way of the dodo. So yes, any pull requests to update docs and other places to point to newer alternatives will be gladly received. With cherries on top.
